name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # ✅ npm으로 변경

      - name: Install dependencies
        run: npm ci  # ✅ npm install --frozen-lockfile와 동일한 역할

      # ✅ TypeScript 타입 검사
      - name: Type check (tsc)
        run: npm run tsc --if-present

      # ✅ ESLint 코드 스타일 검사
      - name: Lint check (eslint)
        run: npm run lint --if-present

      # ✅ 테스트 실행 (선택 사항)
      - name: Run tests
        run: npm test --if-present

      # 기존 빌드
      - name: Install mustache
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Verify build output
        run: |
          if [ ! -d "output" ]; then
            echo "Error: output directory not created"
            exit 1
          fi
          if [ -z "$(ls -A output 2>/dev/null)" ]; then
            echo "Error: output directory is empty"
            exit 1
          fi
          echo "Build output verified successfully"
          ls -la output/

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: youjin-hong
          destination-repository-name: client
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
