name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4  # 최신 버전 사용

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Verify build output
        run: |
          if [ ! -d "output" ]; then
            echo "Error: output directory not created"
            exit 1
          fi
          if [ -z "$(ls -A output 2>/dev/null)" ]; then
            echo "Error: output directory is empty"
            exit 1
          fi
          echo "Build output verified successfully"
          ls -la output/

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: youjin-hong
          destination-repository-name: client
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Verify push success
        run: |
          if [ -z "$DESTINATION_CLONED_DIRECTORY" ]; then
            echo "Error: Push to destination repository may have failed"
            exit 1
          fi
          echo "Push completed successfully to: $DESTINATION_CLONED_DIRECTORY"
